#ifndef _CANIOT_ERRORS_H
#define _CANIOT_ERRORS_H

/* TODO rework all error codes */

/* Tells if error i related to caniot lib */
#define CANIOT_IS_ERR(err)	   ((err == 0U) || (err >= CANIOT_ERROR_BASE && err <= (CANIOT_ERROR_BASE + 0x00FFU)))

#define CANIOT_ERROR_BASE	   0x3A00U

#define CANIOT_OK          0x0000         /* OK */
#define CANIOT_EINVAL	   (CANIOT_ERROR_BASE + 0x0000U)	  /* Invalid argument */
#define CANIOT_ENPROC      (CANIOT_ERROR_BASE + 0x0001U)         /* ERROR UNPROCESSABLE */
#define CANIOT_ECMD        (CANIOT_ERROR_BASE + 0x0002U)         /* ERROR COMMAND */
#define CANIOT_EKEY        (CANIOT_ERROR_BASE + 0x0003U)         /* ERROR KEY (read/write-attribute) */
#define CANIOT_ETIMEOUT    (CANIOT_ERROR_BASE + 0x0004U)         /* ERROR TIMEOUT */
#define CANIOT_EAGAIN      (CANIOT_ERROR_BASE + 0x0005U)         /* ERROR BUSY / EAGAIN */
#define CANIOT_EFMT        (CANIOT_ERROR_BASE + 0x0006U)         /* ERROR FORMAT */
#define CANIOT_EHANDLERC   (CANIOT_ERROR_BASE + 0x0007U)         /* ERROR UNDEFINED COMMAND HANDLER  */
#define CANIOT_EHANDLERT   (CANIOT_ERROR_BASE + 0x0008U)         /* ERROR UNDEFINED TELEMETRY HANDLER */
#define CANIOT_ETELEMETRY  (CANIOT_ERROR_BASE + 0x0009U)         /* ERROR TELEMETRY */
// #define CANIOT_EHDLRCTRL   (CANIOT_ERROR_BASE + 0x000AU)         /* ERROR UNDEFINED CONTROL COMMAND HANDLER  */

#define CANIOT_EEP	   (CANIOT_ERROR_BASE + 0x0017U)	  /* ERROR ENDPOINT */
#define CANIOT_ECMDEP	   (CANIOT_ERROR_BASE + 0x0018U)	  /* ERROR ILLEGAL COMMAND, BROADCAST TO ALL ENDPOINTS */	

#define CANIOT_ENOINIT     (CANIOT_ERROR_BASE + 0x000AU)         /* ERROR NOT INITIALIZED */
#define CANIOT_EDRIVER     (CANIOT_ERROR_BASE + 0x000BU)         /* ERROR DRIVER */
#define CANIOT_EAPI        (CANIOT_ERROR_BASE + 0x000BU)         /* ERROR API */

#define CANIOT_EKEYSECTION (CANIOT_ERROR_BASE + 0x000CU)
#define CANIOT_EKEYATTR    (CANIOT_ERROR_BASE + 0x000DU)
#define CANIOT_EKEYPART    (CANIOT_ERROR_BASE + 0x000EU)

#define CANIOT_EREADONLY   (CANIOT_ERROR_BASE + 0x000FU)

#define CANIOT_ENULL       (CANIOT_ERROR_BASE + 0x0010U)
#define CANIOT_ENULLDRV    (CANIOT_ERROR_BASE + 0x0011U)
#define CANIOT_ENULLAPI    (CANIOT_ERROR_BASE + 0x0012U)
#define CANIOT_ENULLID     (CANIOT_ERROR_BASE + 0x0013U)
#define CANIOT_ENULLDEV    (CANIOT_ERROR_BASE + 0x0014U)
#define CANIOT_ENULLCFG    (CANIOT_ERROR_BASE + 0x0015U)
#define CANIOT_ENULLCTRL   (CANIOT_ERROR_BASE + 0x0016U)
#define CANIOT_ENULLCTRLCB (CANIOT_ERROR_BASE + 0x0016U)

#define CANIOT_EROATTR     (CANIOT_ERROR_BASE + 0x0020U)	  /* ERROR READ-ONLY ATTRIBUTE */
#define CANIOT_EREADATTR   (CANIOT_ERROR_BASE + 0x0021U)         /* ERROR QUERY READ ATTR */
#define CANIOT_EWRITEATTR  (CANIOT_ERROR_BASE + 0x0022U)         /* ERROR QUERY WRITE ATTR */

#define CANIOT_EENOCB      (CANIOT_ERROR_BASE + 0x0032U)         /* ERROR no event handler */
#define CANIOT_EECB        (CANIOT_ERROR_BASE + 0x0033U)         /* ERROR ECCB  */
#define CANIOT_EPQALLOC    (CANIOT_ERROR_BASE + 0x0034U)         /* ERROR PENDING QUERY ALLOCATION  */
#define CANIOT_ENOPQ       (CANIOT_ERROR_BASE + 0x0035U)         /* ERROR NO PENDQING QUERY  */

#define CANIOT_EDEVICE	   (CANIOT_ERROR_BASE + 0x0040U)	  /* ERROR DEVICE */
#define CANIOT_EFRAME	   (CANIOT_ERROR_BASE + 0x0041U)	  /* ERROR FRAME, not a valid caniot frame*/
#define CANIOT_EMLFRM	   (CANIOT_ERROR_BASE + 0x0041U)	  /* ERROR MALFORMED FRAME */

#define CANIOT_ECLASS      (CANIOT_ERROR_BASE + 0x0051U)	  /* ERROR INVALID CLASS */
#define CANIOT_ECFG        (CANIOT_ERROR_BASE + 0x0052U)	  /* ERROR INVALID CONFIGURATION */

#define CANIOT_EBUSY	   CANIOT_EAGAIN

#define CANIOT_ENOTSUP     (CANIOT_ERROR_BASE + 0x0060U)  		/* ERROR NOT SUPPORTED */
#define CANIOT_ENIMPL      CANIOT_ENOTSUP       /* ERROR NOT IMPLEMENTED */

#define CANIOT_PHYS_HYST_INVALID 0x3A70


#define CANIOT_ANY         0x3AFF         /* ANY ERROR + -1 */

#endif /* _CANIOT_ERRORS_H */